# Generated by Django 4.1.7 on 2023-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
