# Generated by Django 4.1.7 on 2023-06-16 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='You must enter a valid phone number (format: +99999999)', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
