# Generated by Django 4.1.7 on 2023-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_code',
            field=models.TextField(max_length=20),
        ),
    ]
