# Generated by Django 4.1.7 on 2023-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0007_alter_user_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_code',
            field=models.CharField(max_length=20),
        ),
    ]
